language: rust
cache:
  directories:
  - $HOME/.cargo
  - $HOME/.cache

rust:
- stable
- nightly

matrix:
  allow_failures:
  - rust: nightly

before_script:
- which sccache || cargo install sccache
- which cargo-make || cargo install cargo-make

env:
- RUSTC_WRAPPER=`which sccache`

script:
- sccache -s
- cargo make ci
- sccache -s
