language: rust

cache:
  directories:
  - $HOME/.cache
  - $HOME/.cargo
  - $HOME/.ccache

addons:
  apt:
    packages:
    # For kcov:
    - binutils-dev
    - libcurl4-openssl-dev
    - libdw-dev
    - libelf-dev

rust:
- stable
- nightly

matrix:
  allow_failures:
  - rust: nightly

before_script:
- which sccache || cargo install sccache
- which cargo-make || cargo install cargo-make
- curl -s https://raw.githubusercontent.com/orenbenkiki/scmf/master/install_kcov.sh | /bin/sh

script:
- export RUSTC_WRAPPER=`which sccache`
- cargo make ci
- sccache --stop-server
