language: rust
cache:
  directories:
  - $HOME/.cargo
  - $HOME/.cache

addons:
  apt:
    packages:
    - kcov

rust:
- stable
# - nightly

matrix:
  allow-failures:
  - rust: nightly

before_script:
- which sccache || cargo install sccache
- which cargo-make || cargo install cargo-make

script:
- export RUSTC_WRAPPER=`which sccache`
- sccache -s
- cargo make ci
- sccache -s
