language: rust

cache:
  directories:
  - $HOME/.cache
  - $HOME/.cargo
  - $HOME/.ccache

addons:
  apt:
    packages:
    - kcov

rust:
- stable
- nightly

matrix:
  allow_failures:
  - rust: nightly

before_script:
- which sccache || cargo install sccache
- which cargo-make || cargo install cargo-make

script:
- export RUSTC_WRAPPER=`which sccache`
- cargo make ci
- sccache --stop-server
