language: rust
cache:
  directories:
  - $HOME/.cargo
  - $HOME/.cache

rust:
- stable
# - nightly

matrix:
  allow-failures:
  - rust: nightly

before_script:
- which sccache || cargo install sccache
- which cargo-make || cargo install cargo-make

env:
- RUSTC_WRAPPER=`which sccache`

script:
- echo $RUSTC_WRAPPER
- export RUSTC_WRAPPER=`which sccache`
- echo $RUSTC_WRAPPER
- sccache -s
- RUSTC_WRAPPER=`which sccache` cargo make ci
- sccache -s
