dev-version-ext = "dev"

pre-release-commit-message =  "chore(release): Release {{version}}."
post-release-commit-message =  "chore(release): Released {{version}}, starting work on {{next_version}}."

pre-release-replacements = [
  {file="README.md", search="v[0-9]+\\.[0-9]+\\.[0-9]+(-dev)?", replace="v{{version}}"},
  {file="src/lib.rs", search="const VERSION: .*", replace="const VERSION: &str = \"{{version}}\";"},
  {file="src/lib.rs", search="/// The current crate version: .*", replace="/// The current crate version: {{version}}"},
]
post-release-replacements = [
  {file="README.md", search="v[0-9]+\\.[0-9]+\\.[0-9]+(-dev)?", replace="v{{version}}"},
  {file="src/lib.rs", search="const VERSION: .*", replace="const VERSION: &str = \"{{next_version}}\";"},
  {file="src/lib.rs", search="/// The current crate version: .*", replace="/// The current crate version: {{next_version}}"},
]
