name: Monthly audit
on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 15 * *'  # 12:30 on the 15th of every month.

jobs:
  montly_audit_dependencies:
    runs-on: ubuntu-latest
    steps:

    - name: Install Rust stable with rustfmt and clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Load cargo cache
      id: cache
      uses: ./.github/actions/cargo-cache

    - name: Install cargo-outdated binary crate
      run: which cargo-outdated || cargo install cargo-outdated

    - name: Install cargo-audit binary crate
      run: which cargo-audit || cargo install cargo-audit

    - name: Monthly audit
      run: make monthly