name: Verified
on: [push]
jobs:
  verify_pushed_commit:
    runs-on: ubuntu-latest
    steps:

    - name: Install Rust stable with rustfmt and clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Load cargo cache
      id: cache
      uses: ./.github/actions/cargo-cache

    - name: Install cargo-tarpaulin binary crate
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest
        use-tool-cache: true

    - name: Install cargo-coverage-annotations binary crate
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-coverage-annotations
        version: latest
        use-tool-cache: true

    - name: Install cargo-udeps binary crate
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
        version: latest
        use-tool-cache: true

    - name: Verify commit
      run: |
        cd ${{ github.workspace }}
        make on-push

    - name: Upload coverage
      run: |
        cd ${{ github.workspace }}
        bash <(curl -s https://codecov.io/bash)