name: Verified
on: [push]
jobs:
  verify_pushed_commit:
    runs-on: ubuntu-latest
    steps:

    - name: Install Rust stable with rustfmt and clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    # This is much faster than using actions-rs/install@v0.1, go figure.
    - name: Install cargo-tarpaulin binary crate
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: '--help'

    - name: Install cargo-coverage-annotations binary crate
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-coverage-annotations
        version: latest
        use-tool-cache: true

    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Verify commit
      run: |
        cd ${{ github.workspace }}
        make ci

    - name: Upload coverage
      run: |
        cd ${{ github.workspace }}
        bash <(curl -s https://codecov.io/bash)